# Opening a File

In [1]:
# Opening a file
file = open("testfile.txt","w") 
print (file.name)
print (file.mode)
file.close()

testfile.txt
w


# Writing/Reading to/from a file



In [2]:
# Writing/Reading to/from a file
file = open("testfile.txt","w") 
file.write("Hello World!")
file = open("testfile.txt","r") 
print (file.read())
file.close()

Hello World!


In [3]:
# Writing/Reading to/from a file
file = open("testfile.txt","w") 
file.writelines("""Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.""")

file = open("testfile.txt","r") 
print (file.readline())  #read a single line
file.close()

Lorem Ipsum is simply dummy text of the printing and typesetting industry. 



## Exercise

In [5]:
# Count the words
def countWord(fileName, word):
    file = open(fileName,"r") 
    count = 0;
    line = file.readline()
    while (line != ""):
        words = line.split()
        for i in words:
            if i == word:
                count = count + 1
        line = file.readline()
    file.close()            
    return count

# Create a file
file = open("testfile.txt","w") 
file.write("""Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.""")

print (countWord('testfile.txt', 'dummy'))

2


# Functions

#### A function is a group of statements that together perform a specific task.

#### Functions are first-class objects in Python, meaning they have attributes and can be referenced and assigned to variables.

In [97]:
t = 1,
#print type(t)

# Function to get sum of two numbers
def add(num1, num2):
    v = num1 + num2
    return v

def test_add():
    assert(add(100, 100) == 200)
    assert(add(100, -100) == 0)
    print "its working!"

print list([1,2,3])

l = [1,2,3,4,5,6,7]

[1, 2, 3]


In [123]:
def double(x):
   x = x * 2
   return x

#print double(10)

def prime():
    x = 2
    while True:
        numdiv = [1 for x in range()]

1

In [41]:
# default value
def addInt(num, what=5, square=False):
    v = num + what
    return v*v if square else v

print addInt(100, square=True, what=10)

12100


In [52]:
def sum_f(*num):
    s = 0
    for n in num:
        s += n
    return s

sum_f(1, 2, 3, 4)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
# Key-value arguments
def showDetails(name, course, duration = '3 months'):
    print('Institute Name: '+ name + ", Course: " + course + ", Duration: " + duration)
    
showDetails(name ='GreyAtom', course ='Full Stack Data Science')

Institute Name: GreyAtom, Course: Full Stack Data Science, Duration: 3 months


In [11]:
# Variable function
def add(num1, num2):
    return num1 + num2

sum = add
print (sum(5, 6))

11


In [63]:
# Nested Functions - function returning function
def outer(a):
    def inner(b):
        return a + b + 5
    return inner

f = outer(20)

def addInt(n):
    def inner(x):
        return x + n
    return inner

add1 = addInt(1)
add2 = addInt(2)
add100 = addInt(100)

def fadd(adder, i):
    return adder(i)

print fadd(add1, 100)

101


In [78]:
# anonymous function - lambda form
# actual form
import math

f = lambda x: math.sqrt(x) if x > 0 else None

def f2(x):
    return math.sqrt(x) if x > 0 else None

### Exercise

In [14]:
# Write a function to count all the ‘VOWELS’ in a given string.
def numOfVowels(string):
    string = string.lower()
    vowels = ['a', 'e', 'i', 'o', 'u']
    count = 0
    for i in range(len(string)):
        if(string[i] in vowels):
            count += 1
    return count

print (numOfVowels("DataScience"))

5


In [15]:
# Calculate TAX amount
# 0 - 250000       - 0%
# 250001 - 500000  - 5%
# 500001 - 1000000 - 20%
# Above 1000000    - 30%
def tax(amount):
    if(amount < 250000):
        return 0
    elif(amount > 250000 and amount <= 500000):
        return amount * 0.05
    elif(amount > 500000 and amount <= 1000000):
        return amount * 0.20
    else:
        return amount * 0.30
    
print ('Enter Amount: ')
amount = float(input())
print ('Tax amount is: '+ str(tax(amount)))

Enter Amount: 
2000000
Tax amount is: 600000.0


## Higher order functions

In [126]:
# map higher order function
# map/reduce/filter
def square(number):
    return number * number

numbers = [1, 2, 3, 4, 5]

numbers_square = map(lambda x: x * x, numbers)
# apply the method on each value of numbers list
print (numbers_square)

[1, 4, 9, 16, 25]


In [17]:
# map using lambda
numbers = [1, 2, 3, 4, 5]
nums = list(map(lambda x: x * x, numbers))
print (nums)

[1, 4, 9, 16, 25]


In [142]:
# filter higher order function
def even(x):
    return x % 2 == 0

numbers = [1, 2, 3, 4, 5]

numbers = [x for x in numbers if even(x)]
numbers = filter(even, numbers)

def f():
    for i in range(100):
        yield i*i

print range(10)
print xrange(100)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
xrange(100)


In [34]:
# filter using lambda
print(list(filter(lambda x: x % 2 == 0, range(2, 25))))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]


In [149]:
# reduce higher order function
from functools import reduce

def add(x, y):
    return x + y

l = [1,2,3,4,5]

reduce(add, [1, 1.0])

def f(x, y):
    return x + 1 

f(0, 1) -> 1
f(1, 2) -> 2
f(2, 3) -> 3

reduce(f, [1,2,3,4,10,100], 0)

6

In [40]:
# reduce using lambda
from functools import reduce
reduce(lambda x,y: x + y, range(5))

10

### Exercise

In [38]:
# Find all the prime numbers between 1 to 50
def getPrime(num):
    for i in range(2,num//2):
        if(num % i) == 0:
            return
    return num    
    
print(list(filter(getPrime, range(50))))

[1, 2, 3, 4, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


####  *args and **kwargs are mostly used in function definitions. *args and **kwargs allow you to pass a variable number of arguments to a function. 


In [42]:
# *arg - use for variable length argument
def test_var_args(f_arg, *argv):
    print ("first normal arg:", f_arg)
    for arg in argv:
        print ("another arg through *argv :", arg)

test_var_args('yasoob','python','eggs','test')

first normal arg: yasoob
another arg through *argv : python
another arg through *argv : eggs
another arg through *argv : test


In [154]:
# **kwargs - use for key value pair argument
def greet_me(*args, **kwargs):
    print args
    print kwargs

greet_me(1,2,3,4,5, c="third", a="first", b="second")

(1, 2, 3, 4, 5)
{'a': 'first', 'c': 'third', 'b': 'second'}


# Exception Handling

#### An exception is an event, which occurs during the execution of a program that disrupts the normal flow of the program's instructions.

In [46]:
try:
   code to be executed
   ...
except Exception-I:
   code to run handle the Exception -I
except Exception-II:
   code to run handle the Exception -II
   ...
else:
   If there is no exception then execute this block. 
finally:

SyntaxError: invalid syntax (<ipython-input-46-1fabf3b2e8d9>, line 2)

In [ ]:
try:
    i = 1/0
except ZeroDivisionError:
    print "Exception occured"
# division by 0
#print("Enter a numerator: ")
#numer = int(input())
#print("Enter a denominator: ")
#denom = int(input())
#try:
#    quotient = numer / denom
#except ZeroDivisionError:
#    print ("denominator can't be 0")
#else:
#    print(quotient)

In [ ]:
try:
    i = 1/0
except ZeroDivisionError:
    print "Exception occured"

In [49]:
# Open non existing file
try:
    file = open('dummy.txt', 'r')
except:   # If exception is not known you can leave this blank                           
    print ("file does't exist")

file does't exist


In [50]:
# division by 0
print("Enter a numerator: ")
numer = int(input())
print("Enter a denominator: ")
denom = int(input())
try:
    quotient = numer / denom
except ZeroDivisionError:
    print ("denominator can't be 0")
finally:
    print ('finally always execute')

Enter a numerator: 
7
Enter a denominator: 
0
denominator can't be 0
finally always execute


In [51]:
class MyError(Exception):
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)

In [52]:
try:
    raise MyError('My Exception Message')
except MyError as e:
    print ('My exception occurred, value:', e.value)

My exception occurred, value: My Exception Message


# Module and Package

#### A module is a file containing Python definitions and statements that allows you to logically group the related Python code.

In [53]:
# Factorial module ...save it in fibo.py
def factorial(num):
    if num < 2:
        return 1
    else:
        return num * factorial(num-1)

In [54]:
import fact
print (fact.factorial(5))

120


In [55]:
# Importing Names from a Module Directly
# caculator.py
def add(a, b):
    return a + b
def sub(a, b):
    return a - b
def divide(a, b):
    return a / b
def multiply(a, b):
    return a * b

In [56]:
from calculator import add, multiply
print (add(4, 3))
print (multiply(4, 3))

7
12


In [57]:
from calculator import *
print (add(4, 3))
print (sub(4, 3))

7
1


In [58]:
# find out where a module is located 
import math
math.__file__

'/Users/sanketpalsule/anaconda/lib/python3.5/lib-dynload/math.so'

In [59]:
# Content of a Module
print (dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']


# Regular Expressions

#### Regular Expressions or regex are a tool for matching patterns in text.

In [37]:
# Regular Expressions
import re

exp = "[9]{3}"

s = "97272424999009999"

m = re.findall(exp, s)
print m


#pattern = re.compile("^[1-9][0-9]{5}$")
#match  = pattern.match("400064")
#print (match.group())

['999', '999']


In [61]:
# Regular Expressions
import re

valid = re.compile("^[1-9][0-9]{5}$")
match  = valid.match("xxxxxx")
print (match)

None


In [62]:
import re
pattern = re.compile("c")

print (re.match(pattern, "abcdef"))   # No match
print (re.search(pattern, "abcdef").group())   # Match

None
c


In [40]:
# Validate email
import re

def isValidEmail(email):
    pattern = re.compile(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
    if re.match(pattern, email):
        return True
    else:
        return False

r = "[0-3]?[0-9]-[0-9]{2}-[0-9]{4}$"  #12-01-1998 (1-31)

print (isValidEmail('info@greyatom.co.in'))
print (isValidEmail('info@greyatom'))

True
False
True


# Object Oriented

#### An object is a person or thing to which a specified action is directed.

In [47]:
class Person(object):  
    # Initializer
   def __init__(self, name, sex, age):
        self.name = name
        self.sex = sex
        self.age = age
        
   # toString method
   def __str__(self):
      return self.name + ' ' + self.sex + ' ' + str(self.age)

   # methods
   def changeName(self, name):
       self.name = name
        
   # methods
   def changeAge(self):
      self.age = self.age + 1
        
person1 = Person('Jane Doe','F',23)
#print person1.name, person1.sex, person1.age
person1.name = "Deepak"
#print person1.name, person1.sex, person1.age

person1.changeAge()
print person1


# new object
#person2 = Person('Bob Smith','M',55) # new object
#print('Person 1: ' + str(person1))   # calling toString method
#person1.changeAge()                  # calling method
#print('Person 1: ' + str(person1))
#person1.changeName('Jane Brown')     # calling method
#print('Person 1: ' + str(person1))
#print(person2)

Deepak F 24


In [65]:
# Inheritance
class Employee(object):
    def __init__(self, name, payRate):
       self.name = name
       self.payRate = payRate

    def __str__(self):
       return self.name + ", " + str(self.payRate)

    def pay(self, hoursWorked):
       return self.payRate * hoursWorked

# Manager IS-A Employee
class Manager(Employee, DeputyEmployee):
   def __init__(self, name, payRate, isSalaried):
      Employee.__init__(self, name, payRate)
      self.salaried = isSalaried

   def __str__(self):
      retStr = Employee.__str__(self)
      retStr += " salaried: " + str(self.salaried)
      return retStr
    
   # Override method
   def pay(self, hoursWorked):
      if self.salaried:
         return self.payRate
      else:
         return super(Manager, self).pay(hoursWorked)

e1 = Employee("John Jones", 10.00)
print(e1)
print("Gross pay: " + str(e1.pay(40)))
m1 = Manager("Jane Smith", 1200, True)
print(m1)
print("Gross pay: " + str(m1.pay(40)))
m2 = Manager("Jim Brown", 20.00, False)
print(m2)
print("Gross pay: " + str(m2.pay(40)))

John Jones, 10.0
Gross pay: 400.0
Jane Smith, 1200 salaried: True
Gross pay: 1200
Jim Brown, 20.0 salaried: False
Gross pay: 800.0


#### Initializers are functions that are automatically called when you create a new instance of a class.

In [2]:
class Greeting:
    def __init__(self, name):
        print ("Constructor called...")
        self.name = name
    def sayHello(self):
        print ("Hello", self.name)
        
x = Greeting("Hello")
x.sayHello()

Constructor called...
('Hello', 'Hello')


In [68]:
# Exercise Account
class Account(object):
   balance = 0
   def __init__(self, acctNumber):
      self.acctNumber = acctNumber

   def __str__(self):
      return "Account number: " + str(self.acctNumber) + "\n" + \
             "Balance: " + str(self.balance)

   def deposit(self, amount):
      self.balance += amount

class Current(Account):
   def __init__(self, acctNumber):
      Account.__init__(self, acctNumber)

   def __str__(self):
      retStr = "Account type: Current\n"
      retStr += Account.__str__(self)
      return retStr

   def withdraw(self, amount):
      if amount > self.balance or self.balance < 15000:
         print("Insufficient funds.")
      else:
         self.balance = self.balance - amount - (amount * 0.1)

class Savings(Account):
   def __init__(self, acctNumber):
      Account.__init__(self, acctNumber)

   def __str__(self):
      retStr = "Account type: Savings\n"
      retStr += Account.__str__(self)
      return retStr

   def withdraw(self, amount):
      if amount > self.balance or self.balance < 1000:
         print("Insufficient funds.")
      else:
         self.balance = self.balance - amount

sa = Savings("123")
print(sa)
sa.deposit(1500)
print(sa)
sa.withdraw(500)
print(sa)

ca = Current("456")
print(ca)
ca.deposit(1500)
print(ca)
ca.withdraw(500)
print(ca)

Account type: Savings
Account number: 123
Balance: 0
Account type: Savings
Account number: 123
Balance: 1500
Account type: Savings
Account number: 123
Balance: 1000
Account type: Current
Account number: 456
Balance: 0
Account type: Current
Account number: 456
Balance: 1500
Insufficient funds.
Account type: Current
Account number: 456
Balance: 1500


# NumPy

#### NumPy is the foundational package for mathematical computing in Python.


In [50]:
# Square the number of list
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

square_values = [x*x for x in list] 
print (square_values)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [55]:
# Square the number of list using numpy
import numpy as np

na = np.array(l)

print na[8]

9


In [59]:
import numpy as np


# We can create a matrix by directly converting a list of lists
my_vector =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]

matrix =  np.array(my_vector)

print (matrix)
print matrix[0][2]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
15


In [62]:
import numpy as np
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
a = np.array(my_matrix, dtype=np.int32)

print (a)

# Print out data type of array
print (a.dtype)

# Print out the shape of array, 3 column , 3 row
print (a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32
(3, 3)


### Exercise

In [ ]:
# Create a vector from the list [10, 20, 30]. Assign the result to the variable vector. 
# Print the dtype, shape and strides.

In [1]:
# Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]].
# Assign the result to the variable matrix. print the dtype, shape and strides.

## NumPy on a datset

In [64]:
# read csv file
import numpy
world_milk = numpy.genfromtxt("world_milk.csv", delimiter=",")
print (world_milk.dtype)
print (world_milk)

float64
[[             nan              nan              nan              nan
               nan]
 [  1.98600000e+03              nan              nan              nan
    0.00000000e+00]
 [  1.98600000e+03              nan              nan              nan
    5.00000000e-01]
 [  1.98600000e+03              nan              nan              nan
    1.62000000e+00]
 [  1.98500000e+03              nan              nan              nan
    6.00000000e-01]
 [  1.98500000e+03              nan              nan              nan
    5.00000000e-01]
 [  1.98500000e+03              nan              nan              nan
    1.00000000e+00]
 [  1.98400000e+03              nan              nan              nan
    8.00000000e-01]
 [  1.98400000e+03              nan              nan              nan
               nan]
 [  1.98400000e+03              nan              nan              nan
    2.50000000e+00]]


In [67]:
# read csv file
import numpy
world_milk = numpy.genfromtxt("world_milk.csv", dtype='|S20', skip_header=1, delimiter=",")
print (world_milk.dtype)
print world_milk[0][0]

|S20
1986


In [75]:
# arange method to create an array
import numpy as np
x = np.arange(0,10)
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
# Even number array
import numpy as np
x = np.arange(0,11,2)
print (x)

[ 0  2  4  6  8 10]


In [69]:
# float
import numpy as np
x = np.arange(0, 10.3, 0.5)

print (x)
print (x.dtype)

[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10. ]
float64


In [74]:
# array of 0
x = np.zeros((2, 10))
#print (x)

# array of 1
y = np.ones(5, dtype=np.int32)
print (y)

# a single dimension array of 1's
##int_array = np.ones(4, dtype=np.int16 )    
#print (int_array)

# a multi dimention array of 1's , 3 rows, 4 columns
#int_array = np.ones( (1,3,4), dtype=np.int16 )    
#print (int_array)

[1 1 1 1 1]


In [75]:
# divide into 3 interval from 0 to 10
np.linspace(0, 10, 10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [80]:
# 50 values between 1 and 10:
print (np.linspace(1, 10))

[  1.           1.18367347   1.36734694   1.55102041   1.73469388
   1.91836735   2.10204082   2.28571429   2.46938776   2.65306122
   2.83673469   3.02040816   3.20408163   3.3877551    3.57142857
   3.75510204   3.93877551   4.12244898   4.30612245   4.48979592
   4.67346939   4.85714286   5.04081633   5.2244898    5.40816327
   5.59183673   5.7755102    5.95918367   6.14285714   6.32653061
   6.51020408   6.69387755   6.87755102   7.06122449   7.24489796
   7.42857143   7.6122449    7.79591837   7.97959184   8.16326531
   8.34693878   8.53061224   8.71428571   8.89795918   9.08163265
   9.26530612   9.44897959   9.63265306   9.81632653  10.        ]


In [81]:
# excluding the endpoint:
print (np.linspace(1, 10, 7, endpoint=False))

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571]


In [77]:
# eye Creates an identity matrix
#print help(np.eye)
print (np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [83]:
# 2 randon numbers
print np.random.rand(10) + 1

[ 1.29491705  1.93296658  1.04298388  1.53527823  1.47332039  1.61723926
  1.92976796  1.56201089  1.66748805  1.72240512]


In [84]:
# randon number array of 5 rows and 5 column
print (np.random.rand(5,5))

[[ 0.92741547  0.2485501   0.17236587  0.87457535  0.21134786]
 [ 0.60456943  0.60568856  0.41006945  0.33424991  0.8688851 ]
 [ 0.85237166  0.42078439  0.90862088  0.28646721  0.28471083]
 [ 0.29814287  0.38129635  0.94470038  0.38195611  0.54816737]
 [ 0.97044668  0.01856429  0.63285698  0.64987577  0.96240688]]


In [85]:
# random integer between 1 to 100 both inclusive
print np.random.randint(1, 100, 10)

[ 1 17 28 63  6 10  3 22 79 83]


In [86]:
# 10 integer array between 1 to 100 both inclusive
print (np.random.randint(1,100,10))

[ 4 98 84 87 84 66  9 80 96 35]


In [88]:
# standard normal distribution
#print help(np.random.randn)
print (np.random.randn(2, 3))

[[ 1.99752717 -0.54450216 -0.69973659]
 [-1.89357669  0.51380989 -0.31643522]]


In [90]:
# indexing one dimentional array
import numpy as np
arr = np.arange(10)
print (arr)
# get the 5th element
print (arr[5])
#Get values in a range
arr[1:9:2]

[0 1 2 3 4 5 6 7 8 9]
5


array([1, 3, 5, 7])

In [91]:
# indexing matrix array
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (arr)
print (arr[1])    # select a row
print (arr[2][2]) #[row], [column]
print (arr[2,2])  # [row, column] 

print arr[x,y]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
9
9


### Exercise

In [90]:
# Assign the amount of milk Uruguayans drank in other milk per capita in 1986 to uruguay_other_1986
import numpy
world_milk = numpy.genfromtxt("world_milk.csv", dtype="|S20", skip_header=1, delimiter=",")
uruguay_other_1986 = world_milk[1, 4]
print (uruguay_other_1986)

b'0.5'


In [91]:
# Assign the country in the third row to third_country. Country is the third column.
import numpy
world_milk = numpy.genfromtxt("world_milk.csv", dtype="|S20", skip_header=1, delimiter=",")
third_country = world_milk[2, 2]
print (third_country)

b'Switzerland'


## Array Slicing

In [92]:
# Slicing one dimensional array
import numpy as np
arr = np.arange(10)
print (arr)
print (arr[0:3])
# start from first index and get every 3rd elemnt
print (arr[1::3])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 4 7]


In [98]:
# Slicing matrix
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
#print arr

# 1st row to 2nd row , 1st column to 3rd column
print arr[1:5:2, :]

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [94]:
# Slicing matrix
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

# 0th row to 2nd row , 1st column to last column
print (arr[:3, 1:])

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [95]:
# Slicing matrix
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

# start from 1st row to every 2nd row, start from 2nd column to every 2nd column
print (arr[1::2, 2::2])

[[ 8 10]]


In [110]:
# Comparing array
import numpy as np
arr = np.arange(11)
#print arr ** 2

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr
print arr + np.array([10, 10, 3])
#print (arr == 10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12  6]
 [14 15  9]
 [17 18 12]]


In [97]:
# Comparing array
import numpy as np
arr = np.arange(11)
print (arr)
print (arr > 5)

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True]


In [98]:
# Comparing matrix
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print (arr == 5)

[[False False False]
 [False  True False]
 [False False False]]


In [113]:
# Comparing with multiple conditions
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#print arr == 2
#print arr == 5
result = (arr == 2) | (arr == 5)
print (result)

[[False  True False]
 [False  True False]
 [False False False]]


In [100]:
# Replacing Values
import numpy as np
vector = np.array([5, 10, 15, 20])
print (vector)
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
print (vector)

[ 5 10 15 20]
[50 50 15 20]


In [101]:
# changing data type
import numpy as np
vector = np.array(["1", "2", "3"])
vector = vector.astype(float)
print (vector)

[ 1.  2.  3.]


### Exercise

In [102]:
#Extract the fifth column from world_milk, and assign it to the variable milk_consumption.
import numpy
milk_consumption = numpy.genfromtxt("world_milk.csv", dtype="|S20", skip_header=1, delimiter=",")
milk_consumption = world_milk[:, 4]
print (milk_consumption)

[b'0' b'0.5' b'1.62' b'0.6' b'0.5' b'1.0' b'0.8' b'' b'2.5']


In [3]:
# Use the astype() method to convert milk_consumption to the float data type.
import numpy
milk_consumption = numpy.genfromtxt("world_milk.csv", dtype="|S20", skip_header=1, delimiter=",")
milk_consumption = world_milk[:, 4]
print (milk_consumption)
milk_consumption_with_value = milk_consumption ==''
milk_consumption[milk_consumption_with_value] = 0  # replace blank with 0print (milk_consumption)
print (milk_consumption.astype(float))

NameError: name 'world_milk' is not defined

## Methods to Operate On Array

In [120]:
# Array: sum(), mean()
import numpy as np
arr = np.array([[10, 12, 41], [17, 49,  2], [46,  3, 19]])

print arr

print arr.sum(axis=1)
#print ('Sum: ', arr.sum())      # sum of array elements
#print ('Mean: ', arr.mean())    # mean of an array

[[10 12 41]
 [17 49  2]
 [46  3 19]]
[63 68 68]


In [121]:
# Array: max(), min(), argmax(), argmin()
import numpy as np
arr = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])
#print ('Max: ',arr.max())       # maximum element in array
#print ('Min: ',arr.min())       # minimum element in array
print ('Argmax: ',arr.argmax()) # index of maximum element
print ('Argmin: ',arr.argmin()) # index of minimum element

('Argmax: ', 4)
('Argmin: ', 5)


In [106]:
# Matrix: sum()
import numpy as np
matrix = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
# 1 means row wise, 0 means column wise
print (matrix.sum(axis=1)) 
print (matrix.sum(axis=0)) 
print (matrix.mean(axis=1)) 
print (matrix.argmin()) 
print (matrix.argmax())

[ 30  75 120]
[60 75 90]
[ 10.  25.  40.]
0
8


In [11]:
#Use the sum() method to calculate the sum of the values in milk_consumption. Assign the result to total_milk.

import numpy
milk_consumption = numpy.genfromtxt("world_milk.csv", dtype="U75", skip_header=1, delimiter=",")
milk_consumption = world_milk[:, 4]
milk_consumption_with_value = milk_consumption !=''
milk_consumption = milk_consumption[milk_consumption_with_value] # remove blank
milk_consumption = milk_consumption.astype(float) # Convert to float
total_milk = milk_consumption.sum()
print (total_milk)

NameError: name 'world_milk' is not defined

In [108]:
# Vectorized Functions
import numpy as np
z = np.array([1, 2, 3])

np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001])

In [110]:
# Vectorized where function
import numpy as np
x = np.random.randn(4)
print (x)
print (np.where(x > 0, 1, 0)) # if x >0 , inser 1 else insert 0

[-1.30708616 -2.44276251 -1.68911542 -0.23608978]
[0 0 0 0]


In [111]:
# apply fuction on array with vectorized
import numpy as np
x = np.random.randn(4)
print (x)
def f(x): return 1 if x > 0 else 0

f = np.vectorize(f)
f(x)

[-1.89781598 -1.00696307  2.43390324 -0.85995713]


array([0, 0, 1, 0])